### ISSUE TITLE
[Chore] Database foreign keys constrain are not defined

### ISSUE THREAD

**Issue by longnd** [htoo-eain-lwin/seeker#18]
Issue
---
Many tables were defined with references to other table, however, the foreign keys constraints were not defined. It cant [guarantee referential integrity](https://edgeguides.rubyonrails.org/active_record_migrations.html#active-record-and-referential-integrity)., is that expected?
For example
https://github.com/htoo-eain-lwin/seeker/blob/4315482b611377e5aaa853960ada2b02487b6de5/db/migrate/20221229182458_create_keywords_users.rb#L3-L6

As you can see in this diagram, there are no foreign keys between tables, except the ones created by ActiveStorage 
![diagram](https://user-images.githubusercontent.com/1896814/211234329-35250c2d-f8b0-449b-b173-9b1879bea29c.svg)

Expected
---
Proper database relationships are defined.

**Comment by htoo-eain-lwin** [comment]
It is not expected. Without foreign key constraints it could lead to inconsistencies and errors in my application because it is possible for records in the keyword_users table to reference non-existent records in the users table. 

@longnd Thanks for pointing out. I will create a PR which will make sure foreign keys constraints are defined.

**Comment by longnd** [comment]
@htoo-eain-lwin thank you for the fix, may I know why those constraints were not defined since the beginning?

and why all foreign keys are nullable, example
https://github.com/htoo-eain-lwin/seeker/blob/2743b59bdb269916c24bea0f37aa626d9e1af656/db/schema.rb#L91-L93

or

https://github.com/htoo-eain-lwin/seeker/blob/2743b59bdb269916c24bea0f37aa626d9e1af656/db/schema.rb#L81-L82

in which case they can be null?

**Comment by htoo-eain-lwin** [comment]
Hello @longnd,

The reason those constraints were not defined since the beginning is I forgot rails pain points about foreign keys constraint. When I created association between models and wrote test, they are working fine. This is definitely life lesson for me about database layer. I totally missed it.  Also all foreign keys are nullable because rails belongs to didn't let the record to create unless I configure. This is convention over configuration again. Thanks again for pointing out these mistakes. I will create a PR and add non nullable foreign keys.

**Comment by htoo-eain-lwin** [comment]
PR #34
