### ISSUE TITLE
[Question] Why does the application need to store the uploaded file

### ISSUE THREAD

**Issue by longnd** [htoo-eain-lwin/seeker#21]
Issue
---
The application uses ActiveStorage to store the uploaded file. The file will not be processed immediately but will be read & parsed later by the `CreateKeywordsAndResultsService`.
Why doesn't the application handle the uploaded file immediately, e.g. read and parse the file, then save the keywords? By doing so, there is no need to keep the files in the system and there is no need clean up them later.

**Comment by htoo-eain-lwin** [comment]
My thought process was that if I store the uploaded file, I can see the differences between successful keywords and failed keywords via checking `search.keywords_from_file` and `search.keywords`.

But the way you mention in other issues #19 and #20 , I don't need to save the file anymore since every keywords are saved after finished uploading the file. It's also better so that we don't need active storage anymore.

@longnd  Thanks for pointing out.
